import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { type MobileJob, useApplyAIApi } from "@/lib/api";

export default function JobsScreen() {
  const { request } = useApplyAIApi(); const [keyword, setKeyword] = useState(""); const [items, setItems] = useState<MobileJob[]>([]); const [loading, setLoading] = useState(true);
  const load = async (q = keyword) => { setLoading(true); try { const params = new URLSearchParams(); if (q.trim()) params.set("keyword", q.trim()); params.set("limit", "30"); const data = await request<{ items: MobileJob[] }>(`/jobs?${params}`); setItems(data.items); } finally { setLoading(false); } };
  useEffect(() => { void load(""); }, [request]);
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.eyebrow}>JOB MARKETPLACE</Text><Text style={styles.title}>Find roles</Text><View style={styles.searchRow}><TextInput style={styles.input} value={keyword} onChangeText={setKeyword} onSubmitEditing={() => load()} placeholder="Role, skill or company" returnKeyType="search"/><Pressable style={styles.button} onPress={() => load()}><Text style={styles.buttonText}>Search</Text></Pressable></View>{loading ? <ActivityIndicator/> : items.map((item) => <View key={item.id} style={styles.card}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.company}>{item.company_name}</Text><Text style={styles.meta}>{[item.location, item.work_mode].filter(Boolean).join(" · ") || "Location flexible"}</Text>{item.saved ? <Text style={styles.saved}>Saved</Text> : null}</View>)}</ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#f6f8fb"},content:{padding:18,gap:12},eyebrow:{fontSize:11,fontWeight:"800",color:"#155eef"},title:{fontSize:30,fontWeight:"800",color:"#10233f"},searchRow:{flexDirection:"row",gap:8},input:{flex:1,backgroundColor:"white",borderWidth:1,borderColor:"#ccd5e1",borderRadius:12,paddingHorizontal:12,paddingVertical:11},button:{backgroundColor:"#155eef",borderRadius:12,paddingHorizontal:16,justifyContent:"center"},buttonText:{color:"white",fontWeight:"700"},card:{padding:16,borderRadius:14,backgroundColor:"white",borderWidth:1,borderColor:"#e2e8f0",gap:5},cardTitle:{fontSize:18,fontWeight:"700",color:"#10233f"},company:{fontWeight:"600",color:"#3d4f66"},meta:{color:"#66758a"},saved:{color:"#087443",fontWeight:"700"}});
