import { useAuth, useClerk } from "@clerk/expo";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useApplyAIApi } from "@/lib/api";

type Me = { email: string; first_name: string | null; last_name: string | null; onboarding_completed: boolean };
type CareerSummary = { verified_fact_count: number; by_category: Record<string, number> };

export default function ProfileScreen(){const{request}=useApplyAIApi();const{signOut}=useClerk();const{userId}=useAuth();const[me,setMe]=useState<Me|null>(null);const[career,setCareer]=useState<CareerSummary|null>(null);const[loading,setLoading]=useState(true);useEffect(()=>{void(async()=>{try{const[meData,careerData]=await Promise.all([request<Me>("/me"),request<CareerSummary>("/career-memory/summary")]);setMe(meData);setCareer(careerData);}finally{setLoading(false);}})();},[request]);if(loading)return <View style={styles.center}><ActivityIndicator/></View>;return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>CANDIDATE PROFILE</Text><Text style={styles.title}>{[me?.first_name,me?.last_name].filter(Boolean).join(" ")||"ApplyAI Candidate"}</Text><Text style={styles.subtitle}>{me?.email}</Text><View style={styles.card}><Text style={styles.cardTitle}>Career Memory</Text><Text style={styles.big}>{career?.verified_fact_count??0}</Text><Text style={styles.subtitle}>verified evidence facts</Text>{Object.entries(career?.by_category??{}).map(([key,value])=><Text style={styles.row} key={key}>{key.replaceAll("_"," ")}: {value}</Text>)}</View><View style={styles.card}><Text style={styles.cardTitle}>Account</Text><Text style={styles.row}>Onboarding: {me?.onboarding_completed?"Complete":"In progress"}</Text><Text style={styles.row}>Identity: {userId??"Signed in"}</Text></View><Pressable style={styles.signout} onPress={()=>void signOut()}><Text style={styles.signoutText}>Sign out</Text></Pressable></ScrollView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:"#f6f8fb"},content:{padding:18,gap:12},center:{flex:1,alignItems:"center",justifyContent:"center"},eyebrow:{fontSize:11,fontWeight:"800",color:"#155eef"},title:{fontSize:30,fontWeight:"800",color:"#10233f"},subtitle:{fontSize:15,lineHeight:22,color:"#53657d"},card:{padding:16,borderRadius:14,backgroundColor:"white",borderWidth:1,borderColor:"#e2e8f0",gap:7},cardTitle:{fontSize:17,fontWeight:"700",color:"#10233f"},big:{fontSize:32,fontWeight:"800",color:"#155eef"},row:{fontSize:14,color:"#53657d"},signout:{marginTop:10,borderWidth:1,borderColor:"#ccd5e1",padding:14,borderRadius:12,alignItems:"center"},signoutText:{fontWeight:"700",color:"#10233f"}});
