"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookOpen, Building2, Headphones, Mic, Pause, Rss, Sparkles, Target } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { toast } from "sonner";
import { Badge, Button, Card, ErrorState, Field, Input, NativeSelect, PageHeader, Progress, Skeleton, Textarea } from "@/components/ui";
import { PlatformApiError, platformApi, type InterviewAttemptResult, type InterviewPhase, type InterviewPreparation, type PodcastEpisode } from "@/lib/api/platform-client";

type Tab = "overview" | "podcast" | "rounds" | "practice" | "research" | "stories" | "setup";
type SpeechResult = { 0: { transcript: string }; isFinal: boolean };
type Recognition = { continuous: boolean; interimResults: boolean; lang: string; start(): void; stop(): void; onresult: ((event: { results: ArrayLike<SpeechResult> }) => void) | null; onend: (() => void) | null; onerror: (() => void) | null };
type RecognitionCtor = new () => Recognition;

function strings(value: unknown): string[] { return Array.isArray(value) ? value.filter((v): v is string => typeof v === "string") : []; }
function record(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function value(value: unknown, fallback = "—"): string { return typeof value === "string" || typeof value === "number" ? String(value) : fallback; }

function Setup({ jobId, prep }: { jobId: string; prep?: InterviewPreparation }) {
  const qc = useQueryClient();
  const [country, setCountry] = useState(prep?.country ?? "United States");
  const [date, setDate] = useState(prep?.interview_date?.slice(0, 16) ?? "");
  const [phase, setPhase] = useState(String(prep?.current_phase_number ?? 1));
  const [name, setName] = useState(prep?.interviewer.name ?? "");
  const [title, setTitle] = useState(prep?.interviewer.title ?? "");
  const [url, setUrl] = useState(prep?.interviewer.url ?? "");
  const save = useMutation<InterviewPreparation, Error, { regenerate: boolean }>({
    mutationFn: ({ regenerate }) => platformApi.interviewIntelligence.bootstrap(jobId, {
      country: country || null,
      interview_date: date ? new Date(date).toISOString() : null,
      current_phase_number: Number(phase),
      interviewer_name: name || null,
      interviewer_title: title || null,
      interviewer_url: url || null,
      regenerate,
    }),
    onSuccess: async () => { await qc.invalidateQueries({ queryKey: ["interview-intelligence", jobId] }); toast.success("Interview preparation saved"); },
    onError: (error) => toast.error(error.message),
  });
  return <Card className="detail-section">
    <div className="section-header"><div><h2>{prep ? "Interview setup" : "Build interview preparation"}</h2><p>Ground every question in this job, your verified Career Memory and the current interview stage.</p></div><Badge tone="info">Evidence locked</Badge></div>
    <div className="form-grid">
      <Field label="Country" htmlFor="ii-country"><Input id="ii-country" value={country} onChange={(e) => setCountry(e.target.value)} /></Field>
      <Field label="Interview date" htmlFor="ii-date"><Input id="ii-date" type="datetime-local" value={date} onChange={(e) => setDate(e.target.value)} /></Field>
      <Field label="Current round" htmlFor="ii-phase"><NativeSelect id="ii-phase" value={phase} onChange={(e) => setPhase(e.target.value)}><option value="1">Recruiter screen</option><option value="2">Hiring manager</option><option value="3">Technical / case panel</option><option value="4">Executive / culture</option></NativeSelect></Field>
      <Field label="Interviewer name" htmlFor="ii-name"><Input id="ii-name" value={name} onChange={(e) => setName(e.target.value)} /></Field>
      <Field label="Interviewer title" htmlFor="ii-title"><Input id="ii-title" value={title} onChange={(e) => setTitle(e.target.value)} /></Field>
      <Field label="Public profile URL" htmlFor="ii-url"><Input id="ii-url" value={url} onChange={(e) => setUrl(e.target.value)} /></Field>
    </div>
    <div className="button-row" style={{ marginTop: 16 }}><Button disabled={save.isPending} onClick={() => save.mutate({ regenerate: false })}><Sparkles size={16}/>{prep ? "Save setup" : "Build prep"}</Button>{prep ? <Button variant="secondary" disabled={save.isPending} onClick={() => save.mutate({ regenerate: true })}>Refresh prep</Button> : null}</div>
  </Card>;
}

function Readiness({ prep }: { prep: InterviewPreparation }) {
  const score = Number(prep.readiness?.overall ?? 45);
  return <Card className="detail-section"><div className="section-header"><div><p className="eyebrow">Readiness</p><h2>{score}%</h2></div><Badge tone={score >= 80 ? "success" : "warning"}>{Number(prep.readiness?.attempt_count ?? 0)} attempts</Badge></div><Progress value={score}/><p className="muted">Practice {Number(prep.readiness?.practice ?? 45)}% · round learning {Number(prep.readiness?.round_learning ?? 0)}% · notes {Number(prep.readiness?.notes ?? 0)}%</p></Card>;
}

function Overview({ prep }: { prep: InterviewPreparation }) {
  const role = record(prep.role_analysis); const resume = record(prep.resume_analysis); const company = record(prep.company_research); const market = record(prep.market_benchmark); const interviewer = record(prep.interviewer.brief);
  const marketSkills = Array.isArray(market.skills) ? market.skills.filter((row): row is Record<string, unknown> => Boolean(row) && typeof row === "object" && !Array.isArray(row)) : [];
  return <div className="detail-grid"><div className="detail-main" style={{ display: "grid", gap: 18 }}>
    <Card className="detail-section"><h2>Role intelligence</h2><div className="button-row">{strings(role.likely_focus).map((item) => <Badge key={item} tone="info">{item}</Badge>)}</div><ul>{strings(role.requirements).slice(0, 8).map((item) => <li key={item}>{item}</li>)}</ul></Card>
    <Card className="detail-section"><h2>Resume evidence</h2><p className="eyebrow">Matched strengths</p>{strings(resume.matched_strengths).map((item) => <p key={item}>✓ {item}</p>)}<p className="eyebrow">Prepare transferability</p>{strings(resume.gaps_to_prepare).map((item) => <p key={item}>→ {item}</p>)}</Card>
    <Card className="detail-section"><h2>Market benchmark</h2><p>{value(market.comparison_job_count, "0")} active comparable roles.</p>{marketSkills.slice(0, 10).map((row) => <div key={String(row.skill)} style={{ display: "flex", justifyContent: "space-between", gap: 12, margin: "8px 0" }}><span>{String(row.skill)}</span><Badge tone={row.candidate_evidence === true ? "success" : "warning"}>{value(row.share_pct, "0")}% · {row.candidate_evidence === true ? "evidence" : "gap"}</Badge></div>)}</Card>
  </div><aside className="detail-aside" style={{ display: "grid", gap: 18, alignContent: "start" }}><Readiness prep={prep}/><Card className="detail-section"><Building2 size={20}/><h2>{value(company.company_name, "Company briefing")}</h2><p>{value(company.description, "Company context is derived from ApplyAI's canonical company and live job corpus.")}</p></Card><Card className="detail-section"><h2>{prep.interviewer.name || "Interviewer brief"}</h2><p>{prep.interviewer.title || "Add interviewer details in Setup."}</p>{strings(interviewer.likely_priorities).map((item) => <Badge key={item}>{item}</Badge>)}<p className="muted">{value(interviewer.evidence_note, "No interviewer-specific claim is invented without reviewed evidence.")}</p></Card></aside></div>;
}

function Podcast({ prep }: { prep: InterviewPreparation }) {
  const [playing, setPlaying] = useState<number | null>(null);
  function stop() { if (typeof window !== "undefined" && "speechSynthesis" in window) window.speechSynthesis.cancel(); setPlaying(null); }
  function play(episode: PodcastEpisode) { if (typeof window === "undefined" || !("speechSynthesis" in window)) { toast.error("Browser speech playback is unavailable."); return; } stop(); const voices = window.speechSynthesis.getVoices(); episode.script.forEach((segment, index) => { const u = new SpeechSynthesisUtterance(segment.text); if (voices.length) u.voice = voices[index % Math.min(voices.length, 4)] ?? null; u.rate = .97; u.pitch = index % 2 ? 1.05 : .94; if (index === episode.script.length - 1) u.onend = () => setPlaying(null); window.speechSynthesis.speak(u); }); setPlaying(episode.episode_number); }
  const feed = typeof window === "undefined" ? platformApi.interviewIntelligence.feedPath(prep.private_feed_token) : `${window.location.origin}${platformApi.interviewIntelligence.feedPath(prep.private_feed_token)}`;
  return <div style={{ display: "grid", gap: 18 }}><Card className="detail-section"><div className="section-header"><div><h2>Private podcast feed</h2><p>Five role-specific episodes with two-host browser playback and a token-protected RSS feed.</p></div><Rss size={20}/></div><div className="button-row"><Button variant="secondary" onClick={() => { void navigator.clipboard.writeText(feed); toast.success("Private feed URL copied"); }}>Copy RSS feed</Button>{playing ? <Button variant="ghost" onClick={stop}><Pause size={16}/>Stop</Button> : null}</div></Card>{prep.episodes.map((episode) => <Card className="detail-section" key={episode.id}><div className="section-header"><div><p className="eyebrow">Episode {episode.episode_number} · ~{episode.duration_estimate_minutes} min</p><h2>{episode.title}</h2></div><Button onClick={() => play(episode)}><Headphones size={16}/>{playing === episode.episode_number ? "Playing" : "Listen"}</Button></div><p>{episode.summary}</p><details><summary>Transcript</summary>{episode.script.map((line, index) => <p key={`${line.speaker}-${index}`}><strong>{line.speaker}:</strong> {line.text}</p>)}</details></Card>)}</div>;
}

function RoundQuiz({ phase }: { phase: InterviewPhase }) {
  const [answers, setAnswers] = useState<Record<string, number>>({}); const [cards, setCards] = useState<Record<number, boolean>>({});
  return <><Card className="detail-section"><h2>Round quiz</h2>{phase.quiz.map((q, qi) => <div key={q.id} style={{ padding: "14px 0", borderTop: qi ? "1px solid var(--line)" : undefined }}><strong>{qi + 1}. {q.question}</strong><div style={{ display: "grid", gap: 8, marginTop: 8 }}>{q.options.map((option, oi) => <Button key={option} variant="secondary" onClick={() => setAnswers((old) => ({ ...old, [q.id]: oi }))}>{option}</Button>)}</div>{answers[q.id] !== undefined ? <p className="muted">{answers[q.id] === q.correct_index ? "Correct. " : "Review. "}{q.explanation}</p> : null}</div>)}</Card><Card className="detail-section"><h2>Flashcards</h2><div className="dashboard-grid">{phase.flashcards.map((card, index) => <button type="button" className="ui-card" key={`${card.front}-${index}`} style={{ textAlign: "left", padding: 18, cursor: "pointer" }} onClick={() => setCards((old) => ({ ...old, [index]: !old[index] }))}><p className="eyebrow">{cards[index] ? "Answer" : "Prompt"}</p><strong>{cards[index] ? card.back : card.front}</strong></button>)}</div></Card></>;
}

function Rounds({ prep }: { prep: InterviewPreparation }) {
  const qc = useQueryClient(); const initial = prep.phases.find((p) => p.phase_number === prep.current_phase_number) ?? prep.phases[0]; const [phaseId, setPhaseId] = useState(initial?.id ?? ""); const phase = prep.phases.find((p) => p.id === phaseId) ?? initial; const [notes, setNotes] = useState(phase?.notes ?? ""); const [went, setWent] = useState(""); const [surprise, setSurprise] = useState(""); const [difficult, setDifficult] = useState(""); const [learned, setLearned] = useState(""); const [different, setDifferent] = useState("");
  const saveNotes = useMutation({ mutationFn: async () => { if (!phase) return; await platformApi.interviewIntelligence.saveNotes(phase.id, notes); }, onSuccess: async () => { await qc.invalidateQueries({ queryKey: ["interview-intelligence", prep.job_id] }); toast.success("Notes saved"); } });
  const reflect = useMutation({ mutationFn: async () => { if (!phase) return; await platformApi.interviewIntelligence.saveReflection(phase.id, { how_it_went: went || null, surprise: surprise || null, difficult_questions: difficult.split("\n").map((s) => s.trim()).filter(Boolean), learned_about_team: learned || null, prepare_differently: different || null }); }, onSuccess: async () => { await qc.invalidateQueries({ queryKey: ["interview-intelligence", prep.job_id] }); toast.success("Reflection carried into the next round"); } });
  if (!phase) return null;
  return <div style={{ display: "grid", gap: 18 }}><Card className="detail-section"><div className="button-row">{prep.phases.map((p) => <Button key={p.id} variant={p.id === phase.id ? "primary" : "secondary"} onClick={() => { setPhaseId(p.id); setNotes(p.notes ?? ""); }}>{p.phase_number}. {p.title}</Button>)}</div></Card>{strings(phase.prep.carry_forward).length ? <Card className="detail-section"><h2>Carry-forward from last round</h2>{strings(phase.prep.carry_forward).map((item) => <p key={item}>→ {item}</p>)}</Card> : null}<div className="detail-grid"><div className="detail-main" style={{ display: "grid", gap: 18 }}><Card className="detail-section"><div className="section-header"><h2>{phase.title}</h2><Badge tone={phase.status === "CURRENT" ? "success" : "neutral"}>{phase.status}</Badge></div><div className="button-row">{strings(phase.prep.focus).map((item) => <Badge key={item}>{item}</Badge>)}</div><ol>{strings(phase.prep.target_questions).map((item) => <li key={item}>{item}</li>)}</ol></Card><RoundQuiz phase={phase}/></div><aside className="detail-aside" style={{ display: "grid", gap: 18, alignContent: "start" }}><Card className="detail-section"><h2>Cheat sheet</h2>{strings(phase.cheat_sheet.remember).map((item) => <p key={item}>• {item}</p>)}<p className="eyebrow">Questions to ask</p>{strings(phase.cheat_sheet.questions_to_ask).map((item) => <p key={item}>• {item}</p>)}</Card><Card className="detail-section"><Field label="Round notes" htmlFor="ii-notes"><Textarea id="ii-notes" rows={10} value={notes} onChange={(e) => setNotes(e.target.value)} /></Field><Button variant="secondary" onClick={() => saveNotes.mutate()}>Save notes</Button></Card></aside></div><Card className="detail-section"><h2>Post-round retrospective</h2><p className="muted">Your difficult questions and preparation changes are carried into the next round.</p><div className="form-grid"><Field label="How did it go?" htmlFor="ii-went"><Textarea id="ii-went" value={went} onChange={(e) => setWent(e.target.value)} /></Field><Field label="What surprised you?" htmlFor="ii-surprise"><Textarea id="ii-surprise" value={surprise} onChange={(e) => setSurprise(e.target.value)} /></Field><Field label="Difficult questions (one per line)" htmlFor="ii-difficult"><Textarea id="ii-difficult" value={difficult} onChange={(e) => setDifficult(e.target.value)} /></Field><Field label="What did you learn about the team?" htmlFor="ii-learned"><Textarea id="ii-learned" value={learned} onChange={(e) => setLearned(e.target.value)} /></Field><Field label="What will you prepare differently?" htmlFor="ii-different"><Textarea id="ii-different" value={different} onChange={(e) => setDifferent(e.target.value)} /></Field></div><Button onClick={() => reflect.mutate()}>Complete round & adapt next prep</Button></Card></div>;
}

function useVoiceAnswer(setAnswer: (value: string) => void) {
  const ref = useRef<Recognition | null>(null); const [listening, setListening] = useState(false);
  function start() { if (typeof window === "undefined") return; const w = window as unknown as { SpeechRecognition?: RecognitionCtor; webkitSpeechRecognition?: RecognitionCtor }; const Ctor = w.SpeechRecognition ?? w.webkitSpeechRecognition; if (!Ctor) { toast.error("Voice transcription is unavailable; type your answer instead."); return; } const r = new Ctor(); let final = ""; r.continuous = true; r.interimResults = true; r.lang = "en-US"; r.onresult = (event) => { let interim = ""; for (let i = 0; i < event.results.length; i += 1) { const row = event.results[i]; if (!row) continue; if (row.isFinal) final += `${row[0]?.transcript ?? ""} `; else interim += row[0]?.transcript ?? ""; } setAnswer(`${final}${interim}`.trim()); }; r.onend = () => setListening(false); r.onerror = () => setListening(false); ref.current = r; r.start(); setListening(true); }
  function stop() { ref.current?.stop(); ref.current = null; setListening(false); }
  return { listening, start, stop };
}

function Practice({ prep }: { prep: InterviewPreparation }) {
  const qc = useQueryClient(); const [phaseId, setPhaseId] = useState(prep.phases.find((p) => p.phase_number === prep.current_phase_number)?.id ?? prep.phases[0]?.id ?? ""); const phase = prep.phases.find((p) => p.id === phaseId) ?? prep.phases[0]; const [questionId, setQuestionId] = useState(phase?.questions[0]?.id ?? ""); const question = phase?.questions.find((q) => q.id === questionId) ?? phase?.questions[0]; const [answer, setAnswer] = useState(""); const [result, setResult] = useState<InterviewAttemptResult | null>(null); const started = useRef<number>(Date.now()); const voice = useVoiceAnswer(setAnswer);
  const submit = useMutation<InterviewAttemptResult, Error, void>({ mutationFn: async () => { if (!question) throw new Error("Practice question unavailable"); return platformApi.interviewIntelligence.submitAttempt(question.id, { answer_text: answer, transcript_source: voice.listening ? "BROWSER_SPEECH" : "TEXT", duration_seconds: Math.max(0, Math.round((Date.now() - started.current) / 1000)) }); }, onSuccess: async (data) => { setResult(data); await qc.invalidateQueries({ queryKey: ["interview-intelligence", prep.job_id] }); toast.success(`Answer scored ${data.score}/100`); } });
  if (!phase || !question) return <Card className="detail-section">No practice questions are available.</Card>;
  function readQuestion() { if (!("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(question!.prompt)); }
  return <div className="detail-grid"><div className="detail-main" style={{ display: "grid", gap: 18 }}><Card className="detail-section"><div className="form-grid"><Field label="Round" htmlFor="ii-practice-phase"><NativeSelect id="ii-practice-phase" value={phase.id} onChange={(e) => { const next = prep.phases.find((p) => p.id === e.target.value); setPhaseId(e.target.value); setQuestionId(next?.questions[0]?.id ?? ""); setResult(null); setAnswer(""); }}>{prep.phases.map((p) => <option value={p.id} key={p.id}>{p.title}</option>)}</NativeSelect></Field><Field label="Question" htmlFor="ii-question"><NativeSelect id="ii-question" value={question.id} onChange={(e) => { setQuestionId(e.target.value); setResult(null); setAnswer(""); started.current = Date.now(); }}>{phase.questions.map((q) => <option value={q.id} key={q.id}>#{q.display_order} · {q.prompt.slice(0, 80)}</option>)}</NativeSelect></Field></div></Card><Card className="detail-section"><p className="eyebrow">Practice out loud</p><h2>{question.prompt}</h2><div className="button-row"><Button variant="secondary" onClick={readQuestion}>Read question</Button>{voice.listening ? <Button variant="danger" onClick={voice.stop}><Pause size={16}/>Stop voice</Button> : <Button variant="secondary" onClick={() => { started.current = Date.now(); voice.start(); }}><Mic size={16}/>Answer by voice</Button>}</div><Field label="Your answer" htmlFor="ii-answer"><Textarea id="ii-answer" rows={12} value={answer} onChange={(e) => setAnswer(e.target.value)} /></Field><Button disabled={!answer.trim() || submit.isPending} onClick={() => submit.mutate()}><Target size={16}/>Score answer</Button></Card>{result ? <Card className="detail-section"><div className="section-header"><h2>{result.score}/100</h2><Badge tone={result.score >= 80 ? "success" : "warning"}>Adaptive feedback</Badge></div><Progress value={result.score}/><p className="eyebrow">Working</p>{result.feedback.strengths?.map((item) => <p key={item}>✓ {item}</p>)}<p className="eyebrow">Improve</p>{result.feedback.improvements?.map((item) => <p key={item}>→ {item}</p>)}{result.feedback.next_followup ? <p><strong>Follow-up:</strong> {result.feedback.next_followup}</p> : null}<details><summary>Evidence-locked model guidance</summary><p>{result.feedback.model_answer}</p></details></Card> : null}</div><aside className="detail-aside"><Readiness prep={prep}/></aside></div>;
}

function Research({ prep }: { prep: InterviewPreparation }) {
  const qc = useQueryClient(); const [title, setTitle] = useState(""); const [url, setUrl] = useState(""); const [snippet, setSnippet] = useState(""); const add = useMutation({ mutationFn: () => platformApi.interviewIntelligence.addResearchSource(prep.job_id, { source_kind: "REVIEWED_PUBLIC_SOURCE", title, url: url || null, snippet: snippet || null }), onSuccess: async () => { setTitle(""); setUrl(""); setSnippet(""); await qc.invalidateQueries({ queryKey: ["interview-intelligence", prep.job_id] }); toast.success("Research evidence added"); } });
  return <div style={{ display: "grid", gap: 18 }}><Card className="detail-section"><h2>Company & interviewer research</h2><p>ApplyAI starts from its canonical company/job evidence. Add reviewed recent news, leadership, earnings, team or interviewer sources without mixing them into verified candidate claims.</p><div className="form-grid"><Field label="Source title" htmlFor="ii-source-title"><Input id="ii-source-title" value={title} onChange={(e) => setTitle(e.target.value)} /></Field><Field label="URL" htmlFor="ii-source-url"><Input id="ii-source-url" value={url} onChange={(e) => setUrl(e.target.value)} /></Field><Field label="Relevant excerpt / note" htmlFor="ii-source-note"><Textarea id="ii-source-note" value={snippet} onChange={(e) => setSnippet(e.target.value)} /></Field></div><Button disabled={!title.trim()} onClick={() => add.mutate()}>Add reviewed source</Button></Card>{prep.research_sources.map((source) => <Card className="detail-section" key={source.id}><div className="section-header"><h2>{source.title}</h2><Badge tone="success">Reviewed</Badge></div>{source.snippet ? <p>{source.snippet}</p> : null}{source.url ? <a href={source.url} target="_blank" rel="noreferrer">Open source ↗</a> : null}</Card>)}</div>;
}

function StoryBank() {
  const qc = useQueryClient(); const stories = useQuery({ queryKey: ["interview-stories"], queryFn: platformApi.interviewIntelligence.stories }); const [title, setTitle] = useState(""); const [situation, setSituation] = useState(""); const [action, setAction] = useState(""); const [result, setResult] = useState(""); const create = useMutation({ mutationFn: () => platformApi.interviewIntelligence.createStory({ title, situation: situation || null, task: null, action: action || null, result: result || null, categories: [], metrics: [], skills: [], source_fact_ids: [], verified: false }), onSuccess: async () => { setTitle(""); setSituation(""); setAction(""); setResult(""); await qc.invalidateQueries({ queryKey: ["interview-stories"] }); toast.success("Story saved"); } }); const rows = Array.isArray(stories.data) ? stories.data : [];
  return <div style={{ display: "grid", gap: 18 }}><Card className="detail-section"><div className="section-header"><div><h2>Persistent STAR story bank</h2><p>Reusable evidence for future interviews.</p></div><BookOpen size={20}/></div><div className="form-grid"><Field label="Story title" htmlFor="ii-story-title"><Input id="ii-story-title" value={title} onChange={(e) => setTitle(e.target.value)} /></Field><Field label="Situation" htmlFor="ii-story-situation"><Textarea id="ii-story-situation" value={situation} onChange={(e) => setSituation(e.target.value)} /></Field><Field label="Action" htmlFor="ii-story-action"><Textarea id="ii-story-action" value={action} onChange={(e) => setAction(e.target.value)} /></Field><Field label="Result" htmlFor="ii-story-result"><Textarea id="ii-story-result" value={result} onChange={(e) => setResult(e.target.value)} /></Field></div><Button disabled={!title.trim()} onClick={() => create.mutate()}>Save story</Button></Card>{rows.map((story) => <Card className="detail-section" key={String(story.id)}><div className="section-header"><h2>{String(story.title)}</h2><Badge tone={story.verified === true ? "success" : "warning"}>{story.verified === true ? "Verified" : "Review"}</Badge></div><p><strong>Situation:</strong> {String(story.situation ?? "—")}</p><p><strong>Action:</strong> {String(story.action ?? "—")}</p><p><strong>Result:</strong> {String(story.result ?? "—")}</p></Card>)}</div>;
}

export function InterviewIntelligenceWorkspace({ jobId }: { jobId: string }) {
  const [tab, setTab] = useState<Tab>("overview"); const query = useQuery({ queryKey: ["interview-intelligence", jobId], queryFn: () => platformApi.interviewIntelligence.get(jobId), retry: false });
  const missing = query.error instanceof PlatformApiError && query.error.status === 404;
  const tabs: Array<[Tab, string]> = useMemo(() => [["overview", "Overview"], ["podcast", "Podcast"], ["rounds", "Rounds"], ["practice", "Practice"], ["research", "Research"], ["stories", "Story bank"], ["setup", "Setup"]], []);
  if (query.isLoading) return <Skeleton className="page-skeleton"/>;
  if (query.isError && !missing) return <ErrorState message={query.error.message} retry={() => query.refetch()}/>;
  if (missing || !query.data) return <><PageHeader eyebrow="Interview Intelligence" title="Build job-specific interview prep" description="Company, role, candidate evidence, round-specific practice and audio preparation in one workspace."/><Setup jobId={jobId}/></>;
  const prep = query.data;
  return <><PageHeader eyebrow="Interview Intelligence" title={prep.job.title} description="Research, role and resume intelligence, podcast prep, round roadmap, quiz, flashcards, voice practice, retrospectives and adaptive readiness." action={<Badge tone="success">{Number(prep.readiness?.overall ?? 45)}% ready</Badge>}/><div className="button-row" style={{ marginBottom: 20 }}>{tabs.map(([key, label]) => <Button key={key} size="small" variant={tab === key ? "primary" : "secondary"} onClick={() => setTab(key)}>{label}</Button>)}</div>{tab === "overview" ? <Overview prep={prep}/> : null}{tab === "podcast" ? <Podcast prep={prep}/> : null}{tab === "rounds" ? <Rounds prep={prep}/> : null}{tab === "practice" ? <Practice prep={prep}/> : null}{tab === "research" ? <Research prep={prep}/> : null}{tab === "stories" ? <StoryBank/> : null}{tab === "setup" ? <Setup jobId={jobId} prep={prep}/> : null}</>;
}
