"use client";

import { BookOpenCheck, BrainCircuit, Building2, Code2, MessageSquareText, RefreshCw, ShieldCheck, Sparkles, Target } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { interviewIntelligenceApi, type CommunityPost, type InterviewQuestion, type PreparationPlan } from "@/lib/api/interview-intelligence-client";
import { Badge, Button, Card, EmptyState, ErrorState, Input, NativeSelect, PageHeader, Progress, Textarea } from "@/components/ui";
import styles from "./interview-intelligence.module.css";

function formatTrack(value: string) {
  return value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (char) => char.toUpperCase());
}

function useAsync<T>(loader: () => Promise<T>, deps: readonly unknown[]) {
  const [data, setData] = useState<T | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    let cancelled = false;
    setLoading(true); setError(null);
    loader().then((value) => { if (!cancelled) setData(value); }).catch((cause: unknown) => { if (!cancelled) setError(cause instanceof Error ? cause.message : "Request failed"); }).finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, deps);
  return { data, setData, error, loading };
}

export function InterviewPrepHub() {
  const capabilities = useAsync(() => interviewIntelligenceApi.capabilities(), []);
  const questions = useAsync(() => interviewIntelligenceApi.questions(new URLSearchParams({ limit: "6" })), []);
  const companies = useAsync(() => interviewIntelligenceApi.companies(), []);
  const progress = useAsync(() => interviewIntelligenceApi.progress(), []);
  if (capabilities.loading || questions.loading || companies.loading || progress.loading) return <div className={styles.loading}>Loading interview intelligence…</div>;
  const error = capabilities.error || questions.error || companies.error || progress.error;
  if (error) return <ErrorState message={error} />;
  const cap = capabilities.data!; const progressData = progress.data!;
  return <div className={styles.shell}>
    <PageHeader eyebrow="Interview intelligence" title="Prepare for the interview you are actually targeting." description="Company-specific intelligence, evidence-backed questions, adaptive practice, job-specific readiness plans, mock interviews, and candidate community—all inside ApplyAI." action={<Link className="ui-button ui-button-primary ui-button-default" href="/interview-prep/questions">Open question bank</Link>} />
    <div className={styles.heroGrid}><Card className={styles.contentCard}><div className={styles.chipRow}><Badge tone="success"><ShieldCheck size={13} /> Clean-room</Badge><Badge tone="info">Evidence + freshness aware</Badge><Badge tone="neutral">6 interview tracks</Badge></div><h2>Your preparation system</h2><p className={styles.muted}>ApplyAI now connects interview questions to companies, candidate evidence, the job you selected, your verified skills, prior attempts, and mock-interview feedback.</p><div className={styles.actions}><Link className="ui-button ui-button-primary ui-button-default" href="/interview-prep/questions"><BookOpenCheck size={16} /> Browse questions</Link><Link className="ui-button ui-button-secondary ui-button-default" href="/interview-prep/community"><MessageSquareText size={16} /> Community</Link></div></Card><div className={styles.metricGrid}><Card className={styles.metric}><strong>{progressData.total_attempts}</strong><span>practice attempts</span></Card><Card className={styles.metric}><strong>{progressData.completed}</strong><span>completed</span></Card><Card className={styles.metric}><strong>{companies.data?.length ?? 0}</strong><span>company collections</span></Card></div></div>
    <section><h2>Practice tracks</h2><div className={styles.grid}>{cap.tracks.map((track) => <Card key={track} className={styles.trackCard}><Badge tone="info">{formatTrack(track)}</Badge><h3>{formatTrack(track)}</h3><p className={styles.muted}>{progressData.by_track[track]?.attempts ?? 0} attempts · {progressData.by_track[track]?.average_score ?? 0}% average</p><Link href={`/interview-prep/questions?track=${track}`}>Practice this track →</Link></Card>)}</div></section>
    <section><div className={styles.jobPanelTop}><div><h2>Fresh question intelligence</h2><p className={styles.muted}>Ranked by frequency, evidence confidence and recency metadata.</p></div><Link href="/interview-prep/questions">View all →</Link></div><div className={styles.questionList}>{questions.data?.items.map((question) => <QuestionRow key={question.id} question={question} />)}</div></section>
    <section><div className={styles.jobPanelTop}><div><h2>Company collections</h2><p className={styles.muted}>See the track mix and question set currently associated with each company.</p></div></div><div className={styles.companies}>{companies.data?.slice(0, 6).map((company) => <Link key={company.slug} href={`/interview-prep/companies/${company.slug}`}><Card className={styles.companyCard}><Building2 size={18} /><h3>{company.name}</h3><p className={styles.muted}>{company.question_count} questions · {company.report_count} evidence reports</p><div className={styles.chipRow}>{Object.keys(company.tracks).slice(0, 3).map((track) => <Badge key={track}>{formatTrack(track)}</Badge>)}</div></Card></Link>)}</div></section>
    {!cap.features.local_code_execution ? <div className={styles.warning}><strong>Safe execution boundary:</strong> Coding and SQL practice are available, but arbitrary candidate code is never executed inside the ApplyAI web/API process. A hardened isolated execution provider is required for Run Code.</div> : null}
  </div>;
}

function QuestionRow({ question }: { question: InterviewQuestion }) {
  return <Link href={`/interview-prep/questions/${question.slug}`}><Card className={styles.questionRow}><div><div className={styles.chipRow}><Badge tone="info">{formatTrack(question.track)}</Badge><Badge>{question.difficulty}</Badge></div><h3>{question.title}</h3><p className={styles.muted}>{question.summary}</p><div className={styles.questionMeta}>{question.companies.map((company) => <Badge key={company}>{company}</Badge>)}{question.skills.slice(0, 3).map((skill) => <Badge key={skill} tone="neutral">{skill}</Badge>)}</div></div><div className={styles.score}><strong>{question.frequency_score}</strong><span className={styles.muted}>frequency</span><Badge tone={question.confidence >= 90 ? "success" : "warning"}>{question.confidence}% confidence</Badge></div></Card></Link>;
}

export function InterviewQuestionBank() {
  const [filters, setFilters] = useState({ q: "", company: "", track: "", difficulty: "", min_confidence: "", sort: "FREQUENCY" });
  const [query, setQuery] = useState(new URLSearchParams());
  const questions = useAsync(() => interviewIntelligenceApi.questions(query), [query.toString()]);
  const companies = useAsync(() => interviewIntelligenceApi.companies(), []);
  function submit(event: FormEvent) { event.preventDefault(); const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => value && params.set(key, value)); setQuery(params); }
  return <div className={styles.shell}><PageHeader eyebrow="Question bank" title="Search interview intelligence." description="Filter by company, track, difficulty and evidence confidence. Question content is clean-room; external reports are retained separately as provenance." /><Card className={styles.contentCard}><form className={styles.toolbar} onSubmit={submit}><Input placeholder="Search questions…" value={filters.q} onChange={(e)=>setFilters({...filters,q:e.target.value})}/><NativeSelect value={filters.company} onChange={(e)=>setFilters({...filters,company:e.target.value})}><option value="">All companies</option>{companies.data?.map((item)=><option key={item.slug} value={item.name}>{item.name}</option>)}</NativeSelect><NativeSelect value={filters.track} onChange={(e)=>setFilters({...filters,track:e.target.value})}><option value="">All tracks</option>{["CODING","SQL","SYSTEM_DESIGN","ML_SYSTEM_DESIGN","OOD","BEHAVIORAL"].map((track)=><option key={track} value={track}>{formatTrack(track)}</option>)}</NativeSelect><NativeSelect value={filters.difficulty} onChange={(e)=>setFilters({...filters,difficulty:e.target.value})}><option value="">All difficulty</option><option>EASY</option><option>MEDIUM</option><option>HARD</option></NativeSelect><NativeSelect value={filters.min_confidence} onChange={(e)=>setFilters({...filters,min_confidence:e.target.value})}><option value="">Any confidence</option><option value="80">80%+</option><option value="90">90%+</option></NativeSelect><NativeSelect value={filters.sort} onChange={(e)=>setFilters({...filters,sort:e.target.value})}><option value="FREQUENCY">Frequency</option><option value="RECENT">Recent</option><option value="CONFIDENCE">Confidence</option></NativeSelect><div className={styles.toolbarActions}><Button type="submit">Apply filters</Button><Button type="button" variant="ghost" onClick={()=>{setFilters({q:"",company:"",track:"",difficulty:"",min_confidence:"",sort:"FREQUENCY"});setQuery(new URLSearchParams());}}>Reset</Button></div></form></Card>{questions.loading?<div className={styles.loading}>Loading question bank…</div>:questions.error?<ErrorState message={questions.error}/>:questions.data?.items.length?<><p className={styles.muted}>{questions.data.total} matching questions</p><div className={styles.questionList}>{questions.data.items.map((question)=><QuestionRow key={question.id} question={question}/>)}</div></>:<EmptyState icon={<BookOpenCheck/>} title="No matching questions" description="Broaden the filters or clear the search."/>}</div>;
}

export function InterviewQuestionDetail({ slug }: { slug: string }) {
  const question = useAsync(() => interviewIntelligenceApi.question(slug), [slug]);
  const [answer,setAnswer]=useState(""); const [code,setCode]=useState(""); const [hint,setHint]=useState<string|null>(null); const [hintLevel,setHintLevel]=useState(0); const [saving,setSaving]=useState(false); const [message,setMessage]=useState<string|null>(null);
  useEffect(()=>{if(question.data)setCode(question.data.starter_code.python??question.data.starter_code.sql??"")},[question.data]);
  if(question.loading)return <div className={styles.loading}>Loading question…</div>; if(question.error||!question.data)return <ErrorState message={question.error??"Question not found"}/>;
  const item=question.data; const codeTrack=item.track==="CODING"||item.track==="SQL";
  async function saveAttempt(){setSaving(true);setMessage(null);try{const attempt=await interviewIntelligenceApi.createAttempt({question_id:item.id,answer,code:codeTrack?code:undefined,language:item.track==="SQL"?"sql":codeTrack?"python":undefined});await interviewIntelligenceApi.updateAttempt(attempt.id,{status:"COMPLETED",answer,code:codeTrack?code:undefined});setMessage("Practice attempt saved to your progress history.")}catch(cause){setMessage(cause instanceof Error?cause.message:"Could not save attempt")}finally{setSaving(false)}}
  async function revealHint(){try{const response=await interviewIntelligenceApi.coach({question_id:item.id,answer,hint_level:hintLevel});setHint(response.hint);setHintLevel(response.next_level)}catch(cause){setMessage(cause instanceof Error?cause.message:"Could not load hint")}}
  return <div className={styles.shell}><PageHeader eyebrow={`${formatTrack(item.track)} · ${item.difficulty}`} title={item.title} description={item.summary} action={<Link className="ui-button ui-button-secondary ui-button-default" href="/interview-prep/questions">Back to bank</Link>}/><div className={styles.questionLayout}><div className={styles.content}><Card className={styles.contentCard}><h2>Interview prompt</h2><p>{item.prompt}</p><div className={styles.chipRow}>{item.skills.map((skill)=><Badge key={skill}>{skill}</Badge>)}</div></Card><Card className={styles.contentCard}><h2>Your response</h2><Textarea className={styles.answer} placeholder="Write your reasoning, assumptions, trade-offs, or behavioral answer…" value={answer} onChange={(e)=>setAnswer(e.target.value)}/>{codeTrack?<><h3>Practice editor</h3><Textarea className={styles.code} value={code} onChange={(e)=>setCode(e.target.value)}/><div className={styles.warning}><Code2 size={15}/> Run Code is intentionally disabled until an isolated sandbox provider is connected. Saving practice never executes this text in the ApplyAI API process.</div></>:null}<div className={styles.actions}><Button onClick={saveAttempt} disabled={saving}>{saving?"Saving…":"Complete attempt"}</Button><Button variant="secondary" onClick={revealHint}><Sparkles size={15}/> Ask coach for hint</Button></div>{hint?<div className={styles.hintBox}>{hint}</div>:null}{message?<p className={styles.muted}>{message}</p>:null}</Card><Card className={styles.contentCard}><h2>Solution framework</h2><ol>{item.solution_outline.map((step)=><li key={step}>{step}</li>)}</ol><h3>Likely follow-ups</h3><ul>{item.follow_ups.map((follow)=><li key={follow}>{follow}</li>)}</ul></Card></div><aside className={styles.sidebar}><Card className={styles.contentCard}><h3>Intelligence signal</h3><p><strong>{item.frequency_score}</strong> frequency score</p><p><strong>{item.confidence}%</strong> evidence confidence</p><p><strong>{item.report_count}</strong> linked reports</p><p className={styles.muted}>{item.last_reported_at?`Last reported ${new Date(item.last_reported_at).toLocaleDateString()}`:"No external report date attached to clean-room seed content."}</p></Card><Card className={styles.contentCard}><h3>Companies</h3><div className={styles.chipRow}>{item.companies.map((company)=><Link key={company} href={`/interview-prep/companies/${company.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`}><Badge tone="info">{company}</Badge></Link>)}</div></Card><Card className={styles.contentCard}><h3>Patterns</h3><div className={styles.chipRow}>{item.patterns.map((pattern)=><Badge key={pattern}>{pattern}</Badge>)}</div></Card></aside></div></div>;
}

export function InterviewCompanyView({ slug }: { slug: string }) {
  const company=useAsync(()=>interviewIntelligenceApi.company(slug),[slug]); if(company.loading)return <div className={styles.loading}>Loading company collection…</div>; if(company.error||!company.data)return <ErrorState message={company.error??"Company collection not found"}/>; return <div className={styles.shell}><PageHeader eyebrow="Company interview radar" title={`${company.data.name} interview intelligence`} description={`${company.data.question_count} clean-room questions across ${Object.keys(company.data.tracks).length} tracks.`}/><div className={styles.metricGrid}>{Object.entries(company.data.tracks).map(([track,count])=><Card key={track} className={styles.metric}><strong>{count}</strong><span>{formatTrack(track)}</span></Card>)}</div><div className={styles.questionList}>{company.data.questions?.map((question)=><QuestionRow key={question.id} question={question}/>)}</div></div>;
}

export function InterviewCommunity() {
  const posts=useAsync(()=>interviewIntelligenceApi.community(),[]); const [company,setCompany]=useState(""); const [title,setTitle]=useState(""); const [body,setBody]=useState(""); const [category,setCategory]=useState("INTERVIEW_EXPERIENCE"); const [status,setStatus]=useState<string|null>(null);
  async function submit(event:FormEvent){event.preventDefault();setStatus(null);try{const created=await interviewIntelligenceApi.createCommunityPost({company:company||undefined,category,title,body});posts.setData([created,...(posts.data??[])]);setTitle("");setBody("");setStatus("Experience shared.")}catch(cause){setStatus(cause instanceof Error?cause.message:"Could not publish")}}
  return <div className={styles.shell}><PageHeader eyebrow="Candidate community" title="Interview experiences become useful intelligence." description="Share process details, compensation context, career advice, and company culture without turning unverified posts directly into canonical questions."/><div className={styles.community}><div className={styles.feed}>{posts.loading?<div className={styles.loading}>Loading community…</div>:posts.error?<ErrorState message={posts.error}/>:posts.data?.map((post)=><Card key={post.id} className={styles.post}><div className={styles.postHeader}><div><div className={styles.chipRow}>{post.company?<Badge tone="info">{post.company}</Badge>:null}<Badge>{formatTrack(post.category)}</Badge></div><h3>{post.title}</h3></div><Button size="small" variant="ghost" onClick={async()=>{const result=await interviewIntelligenceApi.react(post.id);posts.setData((posts.data??[]).map((item)=>item.id===post.id?{...item,reaction_count:result.reaction_count}:item))}}>▲ {post.reaction_count}</Button></div><p>{post.body}</p><div className={styles.postStats}><span>{post.reply_count} replies</span><span>{post.view_count} views</span><span>{new Date(post.created_at).toLocaleDateString()}</span></div></Card>):null}</div><Card className={styles.composer}><h3>Share an experience</h3><form className={styles.form} onSubmit={submit}><Input placeholder="Company (optional)" value={company} onChange={(e)=>setCompany(e.target.value)}/><NativeSelect value={category} onChange={(e)=>setCategory(e.target.value)}><option value="INTERVIEW_EXPERIENCE">Interview experience</option><option value="COMPENSATION">Compensation</option><option value="CAREER_DEVELOPMENT">Career development</option><option value="COMPANY_CULTURE">Company culture</option><option value="OTHER">Other</option></NativeSelect><Input required minLength={5} placeholder="Title" value={title} onChange={(e)=>setTitle(e.target.value)}/><Textarea required minLength={20} placeholder="What happened? Avoid NDA or confidential material." value={body} onChange={(e)=>setBody(e.target.value)}/><Button type="submit">Publish</Button>{status?<p className={styles.muted}>{status}</p>:null}</form></Card></div></div>;
}

export function JobInterviewIntelligencePanel({ jobId }: { jobId: string }) {
  const [plan,setPlan]=useState<PreparationPlan|null>(null); const [busy,setBusy]=useState(false); const [status,setStatus]=useState<string|null>(null); useEffect(()=>{interviewIntelligenceApi.getPlan(jobId).then(setPlan).catch(()=>undefined)},[jobId]);
  async function generate(){setBusy(true);setStatus(null);try{setPlan(await interviewIntelligenceApi.createPlan(jobId))}catch(cause){setStatus(cause instanceof Error?cause.message:"Could not build plan")}finally{setBusy(false)}}
  async function startMock(){setBusy(true);setStatus(null);try{const mock=await interviewIntelligenceApi.startMock(jobId,"TECHNICAL");setStatus(`Mock session created with ${mock.questions.length} questions using ${mock.provider}.`)}catch(cause){setStatus(cause instanceof Error?cause.message:"Could not start mock")}finally{setBusy(false)}}
  return <Card className={styles.jobPanel}><div className={styles.jobPanelTop}><div><Badge tone="info"><BrainCircuit size={13}/> Interview intelligence</Badge><h2>{plan?"Your job-specific preparation plan":"Turn this job into a preparation plan"}</h2><p className={styles.tagline}>Uses the job requirements, your verified ApplyAI skills, and the company/track question graph.</p></div>{plan?<div><strong>{plan.readiness_score}%</strong><Progress value={plan.readiness_score}/></div>:null}</div>{plan?<div className={styles.planGrid}><div><h3>Strengths</h3><div className={styles.chipRow}>{plan.strengths.map((item)=><Badge key={item} tone="success">{item}</Badge>)}</div><h3>Gaps</h3><div className={styles.chipRow}>{plan.gaps.map((item)=><Badge key={item} tone="warning">{item}</Badge>)}</div></div><div className={styles.planActions}>{plan.actions.map((action)=><div className={styles.planAction} key={`${action.order}-${action.track}`}><strong>{formatTrack(action.track)}</strong><p className={styles.muted}>{action.reason}</p>{action.question_count?<Link href={`/interview-prep/questions?track=${action.track}`}>Practice {action.question_count} questions →</Link>:null}</div>)}</div></div>:null}<div className={styles.actions}><Button onClick={generate} disabled={busy}>{busy?"Working…":plan?<><RefreshCw size={15}/> Refresh plan</>:<><Target size={15}/> Build my plan</>}</Button><Button variant="secondary" onClick={startMock} disabled={busy}><BrainCircuit size={15}/> Start adaptive mock</Button><Link className="ui-button ui-button-ghost ui-button-default" href="/interview-prep/questions">Question bank</Link></div>{status?<p className={styles.muted}>{status}</p>:null}</Card>;
}

export function InterviewReportSubmitter() {
  const [company,setCompany]=useState(""); const [role,setRole]=useState(""); const [stage,setStage]=useState(""); const [body,setBody]=useState(""); const [message,setMessage]=useState<string|null>(null);
  return <Card className={styles.contentCard}><h2>Contribute interview intelligence</h2><p className={styles.muted}>User submissions enter a moderation queue and never become canonical questions automatically.</p><form className={styles.form} onSubmit={async(e)=>{e.preventDefault();try{const r=await interviewIntelligenceApi.submitReport({company:company||undefined,role:role||undefined,interview_stage:stage||undefined,body});setMessage(r.duplicate?"We already have this report.":`Submitted for ${r.moderation_status.toLowerCase().replaceAll("_"," ")}.`);setBody("")}catch(cause){setMessage(cause instanceof Error?cause.message:"Could not submit report")}}}><Input placeholder="Company" value={company} onChange={(e)=>setCompany(e.target.value)}/><Input placeholder="Role" value={role} onChange={(e)=>setRole(e.target.value)}/><Input placeholder="Interview stage / round" value={stage} onChange={(e)=>setStage(e.target.value)}/><Textarea minLength={20} required placeholder="Describe the process or question theme. Do not submit NDA/confidential content." value={body} onChange={(e)=>setBody(e.target.value)}/><Button type="submit">Submit for review</Button>{message?<p className={styles.muted}>{message}</p>:null}</form></Card>;
}
