"""candidate milestone one fields

Revision ID: 0db19a1adb4d
Revises: 8f21ae7d52d5
Create Date: 2026-07-28 11:04:00.499877
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0db19a1adb4d'
down_revision: Union[str, None] = '8f21ae7d52d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('current_title', sa.String(length=240), nullable=True))
    op.add_column(
        'jobs',
        sa.Column('search_document', sa.Text(), server_default='', nullable=False),
    )
    op.add_column('jobs', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.add_column(
        'jobs',
        sa.Column(
            'data_origin',
            sa.String(length=48),
            server_default='DEVELOPMENT_SEED',
            nullable=False,
        ),
    )
    op.execute(
        "UPDATE jobs SET search_document = "
        "concat_ws(' ', title, description), "
        "search_vector = to_tsvector('english', concat_ws(' ', title, description))"
    )
    op.create_index('ix_jobs_search_vector', 'jobs', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column(
        'users',
        sa.Column(
            'onboarding_stage',
            sa.String(length=32),
            server_default='ACCOUNT_CREATED',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_stage')
    op.drop_index('ix_jobs_search_vector', table_name='jobs', postgresql_using='gin')
    op.drop_column('jobs', 'data_origin')
    op.drop_column('jobs', 'search_vector')
    op.drop_column('jobs', 'search_document')
    op.drop_column('candidate_profiles', 'current_title')
    # ### end Alembic commands ###
